/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/auth/bootstrap': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Bootstrap Admin */
		post: operations['bootstrap_admin_api_auth_bootstrap_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Login */
		post: operations['login_api_auth_login_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Logout */
		post: operations['logout_api_auth_logout_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Me */
		get: operations['me_api_auth_me_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Sessions */
		get: operations['list_sessions_api_workbench_sessions_get'];
		put?: never;
		/** Create Session */
		post: operations['create_session_api_workbench_sessions_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Session */
		get: operations['get_session_api_workbench_sessions__session_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/candidates': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Candidate Review Items */
		get: operations['list_candidate_review_items_api_workbench_sessions__session_id__candidates_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/graph-candidates': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Session Graph Candidates */
		get: operations['list_session_graph_candidates_api_workbench_sessions__session_id__graph_candidates_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/graph-candidates/{graph_candidate_id}/resume-snapshot': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Graph Candidate Resume Snapshot */
		get: operations['get_graph_candidate_resume_snapshot_api_workbench_sessions__session_id__graph_candidates__graph_candidate_id__resume_snapshot_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/source-connections': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Source Connections */
		get: operations['list_source_connections_api_workbench_source_connections_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/source-connections/liepin': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Liepin Source Connection */
		post: operations['create_liepin_source_connection_api_workbench_source_connections_liepin_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/source-connections/{connection_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Source Connection */
		get: operations['get_source_connection_api_workbench_source_connections__connection_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/source-connections/{connection_id}/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Start Liepin Connection Login */
		post: operations['start_liepin_connection_login_api_workbench_source_connections__connection_id__login_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/source-connections/{connection_id}/login/frame': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Liepin Connection Login Frame */
		get: operations['liepin_connection_login_frame_api_workbench_source_connections__connection_id__login_frame_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/source-connections/{connection_id}/login/snapshot': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Liepin Connection Login Snapshot */
		get: operations['liepin_connection_login_snapshot_api_workbench_source_connections__connection_id__login_snapshot_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/source-connections/{connection_id}/login/input': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Liepin Connection Login Input */
		post: operations['liepin_connection_login_input_api_workbench_source_connections__connection_id__login_input_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/source-connections/{connection_id}/login/complete': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Complete Liepin Connection Login */
		post: operations['complete_liepin_connection_login_api_workbench_source_connections__connection_id__login_complete_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/candidates/{review_item_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Update Candidate Review Item */
		put: operations['update_candidate_review_item_api_workbench_sessions__session_id__candidates__review_item_id__put'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/candidates/{review_item_id}/provider-actions/open': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Open Candidate Provider Action */
		post: operations['open_candidate_provider_action_api_workbench_sessions__session_id__candidates__review_item_id__provider_actions_open_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/candidates/{review_item_id}/detail-open-requests': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Detail Open Request */
		post: operations['create_detail_open_request_api_workbench_sessions__session_id__candidates__review_item_id__detail_open_requests_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/detail-open-requests': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Detail Open Requests */
		get: operations['list_detail_open_requests_api_workbench_detail_open_requests_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/detail-open-requests/{request_id}/approve': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Approve Detail Open Request */
		post: operations['approve_detail_open_request_api_workbench_detail_open_requests__request_id__approve_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/detail-open-requests/{request_id}/reject': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Reject Detail Open Request */
		post: operations['reject_detail_open_request_api_workbench_detail_open_requests__request_id__reject_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/triage': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Requirement Triage */
		get: operations['get_requirement_triage_api_workbench_sessions__session_id__triage_get'];
		/** Update Requirement Triage */
		put: operations['update_requirement_triage_api_workbench_sessions__session_id__triage_put'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/triage/prepare': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Prepare Requirement Triage */
		post: operations['prepare_requirement_triage_api_workbench_sessions__session_id__triage_prepare_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/triage/approve': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Approve Requirement Triage */
		post: operations['approve_requirement_triage_api_workbench_sessions__session_id__triage_approve_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/start': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Start Session Source Runs */
		post: operations['start_session_source_runs_api_workbench_sessions__session_id__start_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/source-runs/liepin/policy': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Liepin Source Run Policy */
		get: operations['get_liepin_source_run_policy_api_workbench_sessions__session_id__source_runs_liepin_policy_get'];
		/** Update Liepin Source Run Policy */
		put: operations['update_liepin_source_run_policy_api_workbench_sessions__session_id__source_runs_liepin_policy_put'];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/security-audit-events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Security Audit Events */
		get: operations['list_security_audit_events_api_workbench_security_audit_events_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/settings': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Settings */
		get: operations['settings_api_workbench_settings_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Events */
		get: operations['list_events_api_workbench_events_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{session_id}/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Session Events */
		get: operations['list_session_events_api_workbench_sessions__session_id__events_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/events/stream': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Stream Events */
		get: operations['stream_events_api_workbench_events_stream_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/workbench/sessions/{workbench_session_id}/events/stream': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Stream Session Events */
		get: operations['stream_session_events_api_workbench_sessions__workbench_session_id__events_stream_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/liepin/compliance-gates': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Compliance Gate */
		post: operations['create_compliance_gate_api_liepin_compliance_gates_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/liepin/compliance-gates/{gate_ref}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Compliance Gate */
		get: operations['get_compliance_gate_api_liepin_compliance_gates__gate_ref__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/liepin/compliance-gates/{gate_ref}/bind-account': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Bind Compliance Gate Account */
		post: operations['bind_compliance_gate_account_api_liepin_compliance_gates__gate_ref__bind_account_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/liepin/compliance-gates/{gate_ref}/verify': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Verify Compliance Gate */
		post: operations['verify_compliance_gate_api_liepin_compliance_gates__gate_ref__verify_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/liepin/connections': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Connection */
		post: operations['create_connection_api_liepin_connections_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/liepin/connections/{connection_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Connection */
		get: operations['get_connection_api_liepin_connections__connection_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/liepin/connections/{connection_id}/login-url': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Get Login Url */
		post: operations['get_login_url_api_liepin_connections__connection_id__login_url_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/liepin/connections/{connection_id}/stream-token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Connection Stream Token */
		post: operations['create_connection_stream_token_api_liepin_connections__connection_id__stream_token_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/liepin/connections/{connection_id}/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Stream Connection Events */
		get: operations['stream_connection_events_api_liepin_connections__connection_id__events_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Run */
		post: operations['create_run_api_runs_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{run_id}/stream-token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Run Stream Token */
		post: operations['create_run_stream_token_api_runs__run_id__stream_token_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{run_id}/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Stream Run Events */
		get: operations['stream_run_events_api_runs__run_id__events_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{run_id}/results': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Run Results */
		get: operations['get_run_results_api_runs__run_id__results_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{run_id}/candidates/{candidate_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Candidate Detail */
		get: operations['get_candidate_detail_api_runs__run_id__candidates__candidate_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/runs/{run_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Run */
		get: operations['get_run_api_runs__run_id__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** CandidateCard */
		CandidateCard: {
			/** Candidateid */
			candidateId: string;
			/** Externalidentityid */
			externalIdentityId: string;
			/** Name */
			name: string;
			/** Title */
			title: string;
			/** Company */
			company: string;
			/** Location */
			location: string;
			/**
			 * Summary
			 * @default
			 */
			summary: string;
		};
		/** CandidateDetailResponse */
		CandidateDetailResponse: {
			candidate: components['schemas']['CandidateCard'];
			resumeView: components['schemas']['CandidateResumeView'];
			aiAnalysis: components['schemas']['ResumeAnalysis'];
		};
		/** CandidateResumeView */
		CandidateResumeView: {
			projection: components['schemas']['ResumeProjection'];
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components['schemas']['ValidationError'][];
		};
		/** LiepinComplianceGateActionResponse */
		LiepinComplianceGateActionResponse: {
			/** Gateref */
			gateRef: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'pending_account_binding' | 'approved' | 'denied' | 'expired';
		};
		/** LiepinComplianceGateConnectionRequest */
		LiepinComplianceGateConnectionRequest: {
			/** Connectionid */
			connectionId: string;
		};
		/** LiepinComplianceGateCreateRequest */
		LiepinComplianceGateCreateRequest: {
			/** Candidatepersonalinfoprocessingbasis */
			candidatePersonalInfoProcessingBasis: string;
			/** Personalinformationprocessor */
			personalInformationProcessor: string;
			/** Operatorauditowner */
			operatorAuditOwner: string;
			/** Accountholderauthorized */
			accountHolderAuthorized: boolean;
			/** Humaninitiatedrecruiting */
			humanInitiatedRecruiting: boolean;
			/** Allowedpurposes */
			allowedPurposes: string[];
			/**
			 * Retentionpolicy
			 * @enum {string}
			 */
			retentionPolicy: 'run_debug_short' | 'workspace_recruiting_record' | 'forbidden_persist';
			/** Deletionsladays */
			deletionSlaDays: number;
			/** Deletionpath */
			deletionPath: string;
			/**
			 * Rawpayloadaccessscope
			 * @enum {string}
			 */
			rawPayloadAccessScope: 'run_only' | 'workspace' | 'admin_only';
			/** Rawdetailretentionallowedafterdebug */
			rawDetailRetentionAllowedAfterDebug: boolean;
			/** Fixtureexportallowed */
			fixtureExportAllowed: boolean;
			/** Policyref */
			policyRef: string;
		};
		/** LiepinComplianceGateResponse */
		LiepinComplianceGateResponse: {
			/** Gateref */
			gateRef: string;
			/** Tenantid */
			tenantId: string;
			/** Workspaceid */
			workspaceId: string;
			/** Actorid */
			actorId: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'pending_account_binding' | 'approved' | 'denied' | 'expired';
			/** Allowedpurposes */
			allowedPurposes: string[];
			/**
			 * Retentionpolicy
			 * @enum {string}
			 */
			retentionPolicy: 'run_debug_short' | 'workspace_recruiting_record' | 'forbidden_persist';
			/** Policyref */
			policyRef: string;
		};
		/** LiepinConnectionCreateRequest */
		LiepinConnectionCreateRequest: {
			/** Compliancegateref */
			complianceGateRef: string;
		};
		/** LiepinConnectionResponse */
		LiepinConnectionResponse: {
			/** Connectionid */
			connectionId: string;
			/** Tenantid */
			tenantId: string;
			/** Workspaceid */
			workspaceId: string;
			/** Actorid */
			actorId: string;
			/** Compliancegateref */
			complianceGateRef: string;
			/** Status */
			status: string;
		};
		/** LiepinLoginUrlResponse */
		LiepinLoginUrlResponse: {
			/** Connectionid */
			connectionId: string;
			/** Loginurl */
			loginUrl: string;
			/**
			 * Handoffstate
			 * @constant
			 */
			handoffState: 'ready_for_browser_login';
		};
		/** LiepinRunResultsResponse */
		LiepinRunResultsResponse: {
			/** Runid */
			runId: string;
			/** Results */
			results?: {
				[key: string]: unknown;
			}[];
		};
		/** ResumeAnalysis */
		ResumeAnalysis: {
			/** Status */
			status: string;
			/** Summary */
			summary: string;
			/** Evidencespans */
			evidenceSpans?: string[];
			/** Riskflags */
			riskFlags?: string[];
		};
		/** ResumeEducationItem */
		ResumeEducationItem: {
			/** School */
			school: string;
			/** Degree */
			degree: string;
			/** Major */
			major: string;
			/** Starttime */
			startTime?: string | null;
			/** Endtime */
			endTime?: string | null;
		};
		/** ResumeProjection */
		ResumeProjection: {
			/** Workyear */
			workYear?: number | null;
			/** Currentlocation */
			currentLocation?: string | null;
			/** Expectedlocation */
			expectedLocation?: string | null;
			/** Jobstate */
			jobState?: string | null;
			/** Expectedsalary */
			expectedSalary?: string | null;
			/** Age */
			age?: number | null;
			/** Education */
			education?: components['schemas']['ResumeEducationItem'][];
			/** Workexperience */
			workExperience?: components['schemas']['ResumeWorkExperienceItem'][];
			/** Worksummaries */
			workSummaries?: string[];
			/** Projectnames */
			projectNames?: string[];
		};
		/** ResumeWorkExperienceItem */
		ResumeWorkExperienceItem: {
			/** Company */
			company: string;
			/** Title */
			title: string;
			/** Duration */
			duration?: string | null;
			/** Starttime */
			startTime?: string | null;
			/** Endtime */
			endTime?: string | null;
			/** Summary */
			summary?: string | null;
		};
		/** RunCreateRequest */
		RunCreateRequest: {
			/** Jobtitle */
			jobTitle: string;
			/** Jdtext */
			jdText: string;
			/**
			 * Sourcingpreferencetext
			 * @default
			 */
			sourcingPreferenceText: string;
			/**
			 * Provider
			 * @default cts
			 * @enum {string}
			 */
			provider: 'cts' | 'liepin';
			/** Connectionid */
			connectionId?: string | null;
			/** Compliancegateref */
			complianceGateRef?: string | null;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
		/** WorkbenchBootstrapRequest */
		WorkbenchBootstrapRequest: {
			/** Email */
			email: string;
			/** Password */
			password: string;
			/** Displayname */
			displayName: string;
		};
		/** WorkbenchBootstrapResponse */
		WorkbenchBootstrapResponse: {
			user: components['schemas']['WorkbenchUserResponse'];
			workspace: components['schemas']['WorkbenchWorkspaceResponse'];
		};
		/** WorkbenchCandidateEvidenceResponse */
		WorkbenchCandidateEvidenceResponse: {
			/** Evidenceid */
			evidenceId: string;
			/** Sourcerunid */
			sourceRunId: string;
			/**
			 * Sourcekind
			 * @enum {string}
			 */
			sourceKind: 'cts' | 'liepin';
			/**
			 * Evidencelevel
			 * @enum {string}
			 */
			evidenceLevel: 'card' | 'detail' | 'final';
			/** Score */
			score?: number | null;
			/** Fitbucket */
			fitBucket?: string | null;
			/** Matchedmusthaves */
			matchedMustHaves: string[];
			/** Matchedpreferences */
			matchedPreferences: string[];
			/** Missingrisks */
			missingRisks: string[];
			/** Strengths */
			strengths: string[];
			/** Weaknesses */
			weaknesses: string[];
			/** Createdat */
			createdAt: string;
		};
		/** WorkbenchCandidateReviewItemResponse */
		WorkbenchCandidateReviewItemResponse: {
			/** Reviewitemid */
			reviewItemId: string;
			/** Sessionid */
			sessionId: string;
			/** Graphcandidateid */
			graphCandidateId?: string | null;
			/**
			 * Canexpandresume
			 * @default false
			 */
			canExpandResume: boolean;
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'new' | 'promising' | 'rejected';
			/** Note */
			note: string;
			/** Displayname */
			displayName: string;
			/** Title */
			title: string;
			/** Company */
			company: string;
			/** Location */
			location: string;
			/** Summary */
			summary: string;
			/** Aggregatescore */
			aggregateScore?: number | null;
			/** Fitbucket */
			fitBucket?: string | null;
			/** Sourcebadges */
			sourceBadges: string[];
			/**
			 * Evidencelevel
			 * @enum {string}
			 */
			evidenceLevel: 'card' | 'detail' | 'final';
			/** Matchedmusthaves */
			matchedMustHaves: string[];
			/** Matchedpreferences */
			matchedPreferences: string[];
			/** Missingrisks */
			missingRisks: string[];
			/** Strengths */
			strengths: string[];
			/** Weaknesses */
			weaknesses: string[];
			/** Evidence */
			evidence: components['schemas']['WorkbenchCandidateEvidenceResponse'][];
			/** Createdat */
			createdAt: string;
			/** Updatedat */
			updatedAt: string;
		};
		/** WorkbenchCandidateReviewItemUpdateRequest */
		WorkbenchCandidateReviewItemUpdateRequest: {
			/** Status */
			status?: ('new' | 'promising' | 'rejected') | null;
			/** Note */
			note?: string | null;
		};
		/** WorkbenchCandidateReviewQueueResponse */
		WorkbenchCandidateReviewQueueResponse: {
			/** Items */
			items: components['schemas']['WorkbenchCandidateReviewItemResponse'][];
		};
		/** WorkbenchDetailOpenCandidateSnapshotResponse */
		WorkbenchDetailOpenCandidateSnapshotResponse: {
			/** Reviewitemid */
			reviewItemId: string;
			/** Displayname */
			displayName: string;
			/** Title */
			title: string;
			/** Company */
			company: string;
			/** Location */
			location: string;
			/** Summary */
			summary: string;
			/** Aggregatescore */
			aggregateScore?: number | null;
			/**
			 * Evidencelevel
			 * @enum {string}
			 */
			evidenceLevel: 'card' | 'detail' | 'final';
			/** Sourcebadges */
			sourceBadges: string[];
			/** Matchedmusthaves */
			matchedMustHaves: string[];
			/** Matchedpreferences */
			matchedPreferences: string[];
			/** Missingrisks */
			missingRisks: string[];
		};
		/** WorkbenchDetailOpenLedgerResponse */
		WorkbenchDetailOpenLedgerResponse: {
			/** Ledgerid */
			ledgerId: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'planned' | 'leased' | 'opened' | 'skipped' | 'blocked' | 'failed' | 'maybe_used';
			/** Budgetday */
			budgetDay: string;
			/** Leaseexpiresat */
			leaseExpiresAt?: string | null;
		};
		/** WorkbenchDetailOpenRejectRequest */
		WorkbenchDetailOpenRejectRequest: {
			/**
			 * Reason
			 * @default
			 */
			reason: string;
		};
		/** WorkbenchDetailOpenRequestCreateRequest */
		WorkbenchDetailOpenRequestCreateRequest: {
			/** Idempotencykey */
			idempotencyKey?: string | null;
		};
		/** WorkbenchDetailOpenRequestListResponse */
		WorkbenchDetailOpenRequestListResponse: {
			/** Requests */
			requests: components['schemas']['WorkbenchDetailOpenRequestResponse'][];
		};
		/** WorkbenchDetailOpenRequestResponse */
		WorkbenchDetailOpenRequestResponse: {
			/** Requestid */
			requestId: string;
			/** Sessionid */
			sessionId: string;
			/** Reviewitemid */
			reviewItemId: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'pending' | 'approved' | 'rejected' | 'bypassed' | 'blocked' | 'expired';
			/**
			 * Detailopenmode
			 * @enum {string}
			 */
			detailOpenMode: 'human_confirm' | 'bypass_confirm';
			/** Decisionnote */
			decisionNote?: string | null;
			candidate?: components['schemas']['WorkbenchDetailOpenCandidateSnapshotResponse'] | null;
			/** Blockedreason */
			blockedReason?: string | null;
			ledger?: components['schemas']['WorkbenchDetailOpenLedgerResponse'] | null;
			providerAction?: components['schemas']['WorkbenchProviderActionResponse'] | null;
			/** Createdat */
			createdAt: string;
			/** Updatedat */
			updatedAt: string;
		};
		/** WorkbenchEventListResponse */
		WorkbenchEventListResponse: {
			/** Events */
			events: components['schemas']['WorkbenchEventResponse'][];
		};
		/** WorkbenchEventResponse */
		WorkbenchEventResponse: {
			/** Globalseq */
			globalSeq: number;
			/** Sessionseq */
			sessionSeq?: number | null;
			/** Sessionid */
			sessionId?: string | null;
			/** Sourcerunid */
			sourceRunId?: string | null;
			/** Sourcekind */
			sourceKind?: ('cts' | 'liepin') | null;
			/** Eventname */
			eventName: string;
			/** Schemaversion */
			schemaVersion: string;
			/** Idempotencykey */
			idempotencyKey?: string | null;
			/** Payload */
			payload: {
				[key: string]: unknown;
			};
			/** Occurredat */
			occurredAt: string;
			/** Createdat */
			createdAt: string;
		};
		/** WorkbenchGraphCandidateCoverageResponse */
		WorkbenchGraphCandidateCoverageResponse: {
			/** Sourceresultidsseen */
			sourceResultIdsSeen: string[];
			/** Missingsafeidentitycount */
			missingSafeIdentityCount: number;
			/** Missingsnapshotcount */
			missingSnapshotCount: number;
			/** Forbiddensnapshotcount */
			forbiddenSnapshotCount: number;
			/** Droppedrows */
			droppedRows: number;
		};
		/** WorkbenchGraphCandidateListResponse */
		WorkbenchGraphCandidateListResponse: {
			/** Nodeid */
			nodeId: string;
			nodeScope: components['schemas']['WorkbenchGraphCandidateNodeScope'];
			/** Items */
			items: components['schemas']['WorkbenchGraphCandidateSummaryResponse'][];
			/** Nextcursor */
			nextCursor?: string | null;
			/** Totalsourceresults */
			totalSourceResults: number;
			/** Totalgraphcandidates */
			totalGraphCandidates: number;
			/** Totalestimate */
			totalEstimate?: number | null;
			coverage: components['schemas']['WorkbenchGraphCandidateCoverageResponse'];
			/** Truncated */
			truncated: boolean;
			/** Generatedat */
			generatedAt: string;
			/**
			 * Recoverystate
			 * @default ready
			 * @enum {string}
			 */
			recoveryState: 'ready' | 'recoverable_empty';
			/** Recoveryreason */
			recoveryReason?: string | null;
		};
		/** WorkbenchGraphCandidateNodeScope */
		WorkbenchGraphCandidateNodeScope: {
			/** Sessionid */
			sessionId: string;
			/**
			 * Source
			 * @enum {string}
			 */
			source: 'cts' | 'liepin' | 'all';
			/** Roundid */
			roundId?: string | null;
			/**
			 * Nodekind
			 * @enum {string}
			 */
			nodeKind: 'recall' | 'scoring' | 'final' | 'liepin_card' | 'detail_approval';
		};
		/** WorkbenchGraphCandidateResumeSnapshotResponse */
		WorkbenchGraphCandidateResumeSnapshotResponse: {
			/** Graphcandidateid */
			graphCandidateId: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'ready' | 'snapshot_forbidden' | 'snapshot_not_found';
			/** Reason */
			reason?: string | null;
			/**
			 * Sourcecompleteness
			 * @default unavailable
			 * @enum {string}
			 */
			sourceCompleteness: 'cts_raw_payload' | 'normalized_fallback' | 'unavailable';
			originalResume?: components['schemas']['WorkbenchOriginalResumeResponse'] | null;
			profile?: components['schemas']['WorkbenchResumeSnapshotProfileResponse'] | null;
			/** Workexperience */
			workExperience?: components['schemas']['WorkbenchResumeSnapshotWorkExperienceResponse'][];
			/** Education */
			education?: components['schemas']['WorkbenchResumeSnapshotEducationResponse'][];
			/** Projects */
			projects?: components['schemas']['WorkbenchResumeSnapshotProjectResponse'][];
			/** Skills */
			skills?: string[];
			/** Sourceevidence */
			sourceEvidence?: components['schemas']['WorkbenchResumeSnapshotSourceEvidenceResponse'][];
		};
		/** WorkbenchGraphCandidateSummaryResponse */
		WorkbenchGraphCandidateSummaryResponse: {
			/** Graphcandidateid */
			graphCandidateId: string;
			/**
			 * Sourcekind
			 * @enum {string}
			 */
			sourceKind: 'cts' | 'liepin';
			/** Sourcerunid */
			sourceRunId: string;
			/**
			 * Nodekind
			 * @enum {string}
			 */
			nodeKind: 'recall' | 'scoring' | 'final' | 'liepin_card' | 'detail_approval';
			/** Roundno */
			roundNo?: number | null;
			/** Lanetype */
			laneType?: string | null;
			/** Queryrole */
			queryRole?: string | null;
			/**
			 * Relationshipkind
			 * @enum {string}
			 */
			relationshipKind:
				| 'recalled'
				| 'new'
				| 'scored'
				| 'fit'
				| 'not_fit'
				| 'final'
				| 'detail_requested';
			/** Displayname */
			displayName: string;
			/** Title */
			title: string;
			/** Company */
			company: string;
			/** Location */
			location: string;
			/** Sourcebadges */
			sourceBadges: string[];
			/** Score */
			score?: number | null;
			/** Fitbucket */
			fitBucket?: string | null;
			/** Summary */
			summary: string;
			/** Matchedmusthaves */
			matchedMustHaves: string[];
			/** Strengths */
			strengths: string[];
			/** Missingrisks */
			missingRisks: string[];
			/** Reviewitemid */
			reviewItemId?: string | null;
			/** Evidencelevel */
			evidenceLevel?: ('card' | 'detail' | 'final') | null;
			/** Detailopenrequestid */
			detailOpenRequestId?: string | null;
			/** Canexpandresume */
			canExpandResume: boolean;
			/** Canmarkpromising */
			canMarkPromising: boolean;
			/** Canreject */
			canReject: boolean;
			/** Cansavenote */
			canSaveNote: boolean;
			/** Canrequestdetail */
			canRequestDetail: boolean;
			/** Canopenprovider */
			canOpenProvider: boolean;
		};
		/** WorkbenchLiepinLoginHandoffResponse */
		WorkbenchLiepinLoginHandoffResponse: {
			/** Connectionid */
			connectionId: string;
			/**
			 * Sourcekind
			 * @constant
			 */
			sourceKind: 'liepin';
			/**
			 * Status
			 * @enum {string}
			 */
			status:
				| 'login_required'
				| 'login_in_progress'
				| 'verification_required'
				| 'connected'
				| 'expired'
				| 'blocked'
				| 'disconnected';
			/**
			 * Handoffmode
			 * @constant
			 */
			handoffMode: 'server_managed_browser';
			/**
			 * Handoffstate
			 * @enum {string}
			 */
			handoffState: 'login_in_progress' | 'relay_pending_worker' | 'safe_frame_available';
			/** Safeframeurl */
			safeFrameUrl?: string | null;
			/** Warningcode */
			warningCode?: string | null;
			/** Warningmessage */
			warningMessage?: string | null;
		};
		/** WorkbenchLiepinLoginRelayInputRequest */
		WorkbenchLiepinLoginRelayInputRequest: {
			/**
			 * Action
			 * @enum {string}
			 */
			action: 'click' | 'type' | 'key';
			/** X */
			x?: number | null;
			/** Y */
			y?: number | null;
			/** Text */
			text?: string | null;
			/** Key */
			key?: string | null;
		};
		/** WorkbenchLoginRequest */
		WorkbenchLoginRequest: {
			/** Email */
			email: string;
			/** Password */
			password: string;
		};
		/** WorkbenchMeResponse */
		WorkbenchMeResponse: {
			user: components['schemas']['WorkbenchUserResponse'];
		};
		/** WorkbenchOriginalResumeFieldResponse */
		WorkbenchOriginalResumeFieldResponse: {
			/** Key */
			key: string;
			/** Label */
			label: string;
			/** Value */
			value: string;
		};
		/** WorkbenchOriginalResumeItemResponse */
		WorkbenchOriginalResumeItemResponse: {
			/** Title */
			title: string;
			/** Fields */
			fields?: components['schemas']['WorkbenchOriginalResumeFieldResponse'][];
		};
		/** WorkbenchOriginalResumeResponse */
		WorkbenchOriginalResumeResponse: {
			/** Sourcekind */
			sourceKind: string;
			/** Sections */
			sections?: components['schemas']['WorkbenchOriginalResumeSectionResponse'][];
		};
		/** WorkbenchOriginalResumeSectionResponse */
		WorkbenchOriginalResumeSectionResponse: {
			/** Title */
			title: string;
			/** Items */
			items?: components['schemas']['WorkbenchOriginalResumeItemResponse'][];
		};
		/** WorkbenchProviderActionResponse */
		WorkbenchProviderActionResponse: {
			/**
			 * Actionkind
			 * @constant
			 */
			actionKind: 'managed_browser';
			/**
			 * Sourcekind
			 * @constant
			 */
			sourceKind: 'liepin';
			/** Connectionid */
			connectionId: string;
			/** Reviewitemid */
			reviewItemId: string;
			/**
			 * Budgetimpact
			 * @enum {string}
			 */
			budgetImpact: 'none' | 'reserved';
			/** Message */
			message: string;
		};
		/** WorkbenchRequirementTriageResponse */
		WorkbenchRequirementTriageResponse: {
			/** Sessionid */
			sessionId: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'draft' | 'approved';
			/** Musthaves */
			mustHaves: string[];
			/** Nicetohaves */
			niceToHaves: string[];
			/** Synonyms */
			synonyms: string[];
			/** Seniorityfilters */
			seniorityFilters: string[];
			/** Exclusions */
			exclusions: string[];
			/** Generatedqueryhints */
			generatedQueryHints: string[];
			/** Createdat */
			createdAt: string;
			/** Updatedat */
			updatedAt: string;
			/** Approvedat */
			approvedAt?: string | null;
		};
		/** WorkbenchRequirementTriageUpdateRequest */
		WorkbenchRequirementTriageUpdateRequest: {
			/** Musthaves */
			mustHaves?: string[];
			/** Nicetohaves */
			niceToHaves?: string[];
			/** Synonyms */
			synonyms?: string[];
			/** Seniorityfilters */
			seniorityFilters?: string[];
			/** Exclusions */
			exclusions?: string[];
			/** Generatedqueryhints */
			generatedQueryHints?: string[];
		};
		/** WorkbenchResumeSnapshotEducationResponse */
		WorkbenchResumeSnapshotEducationResponse: {
			/** School */
			school: string;
			/** Degree */
			degree?: string | null;
			/** Major */
			major?: string | null;
		};
		/** WorkbenchResumeSnapshotProfileResponse */
		WorkbenchResumeSnapshotProfileResponse: {
			/** Displayname */
			displayName: string;
			/** Headline */
			headline: string;
			/** Company */
			company: string;
			/** Location */
			location: string;
			/** Summary */
			summary: string;
		};
		/** WorkbenchResumeSnapshotProjectResponse */
		WorkbenchResumeSnapshotProjectResponse: {
			/** Name */
			name: string;
			/** Summary */
			summary?: string | null;
		};
		/** WorkbenchResumeSnapshotSourceEvidenceResponse */
		WorkbenchResumeSnapshotSourceEvidenceResponse: {
			/** Label */
			label: string;
			/** Text */
			text: string;
		};
		/** WorkbenchResumeSnapshotWorkExperienceResponse */
		WorkbenchResumeSnapshotWorkExperienceResponse: {
			/** Company */
			company: string;
			/** Title */
			title: string;
			/** Duration */
			duration?: string | null;
			/** Summary */
			summary?: string | null;
		};
		/** WorkbenchRuntimeSourceLaneStateResponse */
		WorkbenchRuntimeSourceLaneStateResponse: {
			/**
			 * Sourcekind
			 * @enum {string}
			 */
			sourceKind: 'cts' | 'liepin';
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'pending' | 'running' | 'completed' | 'partial' | 'blocked' | 'failed' | 'cancelled';
			/** Eventtype */
			eventType?: string | null;
			/** Eventseq */
			eventSeq?: number | null;
			/**
			 * Cardsseencount
			 * @default 0
			 */
			cardsSeenCount: number;
			/**
			 * Cardsfilteredcount
			 * @default 0
			 */
			cardsFilteredCount: number;
			/**
			 * Candidatescount
			 * @default 0
			 */
			candidatesCount: number;
			/**
			 * Detailrecommendationscount
			 * @default 0
			 */
			detailRecommendationsCount: number;
			/** Detailstate */
			detailState?:
				| ('detail_recommended' | 'pending_approval' | 'leased' | 'completed' | 'blocked')
				| null;
		};
		/** WorkbenchRuntimeSourceStateResponse */
		WorkbenchRuntimeSourceStateResponse: {
			/** Selectedsourcekinds */
			selectedSourceKinds: ('cts' | 'liepin')[];
			/**
			 * Coveragestatus
			 * @enum {string}
			 */
			coverageStatus: 'pending' | 'complete' | 'degraded' | 'empty';
			/** Finalizationrevision */
			finalizationRevision?: number | null;
			/** Finalizationreasoncode */
			finalizationReasonCode?: string | null;
			/**
			 * Identitymergecount
			 * @default 0
			 */
			identityMergeCount: number;
			/**
			 * Ambiguousduplicatecount
			 * @default 0
			 */
			ambiguousDuplicateCount: number;
			/**
			 * Canonicalresumeselectedcount
			 * @default 0
			 */
			canonicalResumeSelectedCount: number;
			/** Sources */
			sources: components['schemas']['WorkbenchRuntimeSourceLaneStateResponse'][];
		};
		/** WorkbenchSecurityAuditEventListResponse */
		WorkbenchSecurityAuditEventListResponse: {
			/** Events */
			events: components['schemas']['WorkbenchSecurityAuditEventResponse'][];
		};
		/** WorkbenchSecurityAuditEventResponse */
		WorkbenchSecurityAuditEventResponse: {
			/** Auditid */
			auditId: number;
			/** Actoruserid */
			actorUserId?: string | null;
			/** Actorrole */
			actorRole?: string | null;
			/** Workspaceid */
			workspaceId: string;
			/** Requestip */
			requestIp?: string | null;
			/** Useragent */
			userAgent?: string | null;
			/** Targettype */
			targetType: string;
			/** Targetid */
			targetId?: string | null;
			/** Action */
			action: string;
			/** Result */
			result: string;
			/** Reasoncode */
			reasonCode?: string | null;
			/** Metadata */
			metadata: {
				[key: string]: unknown;
			};
			/** Createdat */
			createdAt: string;
		};
		/** WorkbenchSessionCreateRequest */
		WorkbenchSessionCreateRequest: {
			/** Jobtitle */
			jobTitle: string;
			/** Jdtext */
			jdText: string;
			/**
			 * Notes
			 * @default
			 */
			notes: string;
			/** Sourcekinds */
			sourceKinds?: ('cts' | 'liepin')[] | null;
		};
		/** WorkbenchSessionListResponse */
		WorkbenchSessionListResponse: {
			/** Sessions */
			sessions: components['schemas']['WorkbenchSessionResponse'][];
		};
		/** WorkbenchSessionResponse */
		WorkbenchSessionResponse: {
			/** Sessionid */
			sessionId: string;
			/** Workspaceid */
			workspaceId: string;
			/** Owneruserid */
			ownerUserId: string;
			/** Jobtitle */
			jobTitle: string;
			/** Jdtext */
			jdText: string;
			/** Notes */
			notes: string;
			/**
			 * Status
			 * @constant
			 */
			status: 'draft';
			requirementTriage: components['schemas']['WorkbenchRequirementTriageResponse'];
			/** Sourceruns */
			sourceRuns: components['schemas']['WorkbenchSourceRunResponse'][];
			/** Sourcecards */
			sourceCards: components['schemas']['WorkbenchSourceCardResponse'][];
			runtimeSourceState?: components['schemas']['WorkbenchRuntimeSourceStateResponse'] | null;
		};
		/** WorkbenchSessionStartBlockedSourceResponse */
		WorkbenchSessionStartBlockedSourceResponse: {
			/** Sourcerunid */
			sourceRunId: string;
			/**
			 * Sourcekind
			 * @enum {string}
			 */
			sourceKind: 'cts' | 'liepin';
			/** Reason */
			reason: string;
		};
		/** WorkbenchSessionStartResponse */
		WorkbenchSessionStartResponse: {
			/** Sessionid */
			sessionId: string;
			/** Sourceruns */
			sourceRuns: components['schemas']['WorkbenchSourceRunStartResponse'][];
			/** Blockedsources */
			blockedSources?: components['schemas']['WorkbenchSessionStartBlockedSourceResponse'][];
		};
		/** WorkbenchSettingsResponse */
		WorkbenchSettingsResponse: {
			/** Workspaceid */
			workspaceId: string;
			/** Sources */
			sources: components['schemas']['WorkbenchSettingsSourceResponse'][];
		};
		/** WorkbenchSettingsSourceResponse */
		WorkbenchSettingsSourceResponse: {
			/**
			 * Sourcekind
			 * @enum {string}
			 */
			sourceKind: 'cts' | 'liepin';
			/** Label */
			label: string;
			/** Enabled */
			enabled: boolean;
			/** Authrequired */
			authRequired: boolean;
		};
		/** WorkbenchSourceCardResponse */
		WorkbenchSourceCardResponse: {
			/** Sourcerunid */
			sourceRunId: string;
			/**
			 * Sourcekind
			 * @enum {string}
			 */
			sourceKind: 'cts' | 'liepin';
			/** Label */
			label: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'queued' | 'blocked' | 'running' | 'completed' | 'failed';
			/**
			 * Authstate
			 * @enum {string}
			 */
			authState: 'not_required' | 'login_required';
			/** Warningcode */
			warningCode?: string | null;
			/** Warningmessage */
			warningMessage?: string | null;
			/**
			 * Cardsscannedcount
			 * @default 0
			 */
			cardsScannedCount: number;
			/**
			 * Uniquecandidatescount
			 * @default 0
			 */
			uniqueCandidatesCount: number;
			/**
			 * Detailopenusedcount
			 * @default 0
			 */
			detailOpenUsedCount: number;
			/**
			 * Detailopenblockedcount
			 * @default 0
			 */
			detailOpenBlockedCount: number;
			/** Connectionid */
			connectionId?: string | null;
			/** Connectionstatus */
			connectionStatus?:
				| (
						| 'login_required'
						| 'login_in_progress'
						| 'verification_required'
						| 'connected'
						| 'expired'
						| 'blocked'
						| 'disconnected'
				  )
				| null;
			/** Connectionwarningcode */
			connectionWarningCode?: string | null;
			/** Connectionwarningmessage */
			connectionWarningMessage?: string | null;
		};
		/** WorkbenchSourceConnectionListResponse */
		WorkbenchSourceConnectionListResponse: {
			/** Connections */
			connections: components['schemas']['WorkbenchSourceConnectionResponse'][];
		};
		/** WorkbenchSourceConnectionResponse */
		WorkbenchSourceConnectionResponse: {
			/** Connectionid */
			connectionId: string;
			/**
			 * Sourcekind
			 * @enum {string}
			 */
			sourceKind: 'cts' | 'liepin';
			/** Label */
			label: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status:
				| 'login_required'
				| 'login_in_progress'
				| 'verification_required'
				| 'connected'
				| 'expired'
				| 'blocked'
				| 'disconnected';
			/** Warningcode */
			warningCode?: string | null;
			/** Warningmessage */
			warningMessage?: string | null;
			/** Createdat */
			createdAt: string;
			/** Updatedat */
			updatedAt: string;
			/** Connectedat */
			connectedAt?: string | null;
		};
		/** WorkbenchSourceRunJobResponse */
		WorkbenchSourceRunJobResponse: {
			/** Jobid */
			jobId: string;
			/** Sourcerunid */
			sourceRunId: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'queued' | 'running' | 'completed' | 'failed';
			/** Attemptcount */
			attemptCount: number;
			/** Errormessage */
			errorMessage?: string | null;
			/** Createdat */
			createdAt: string;
			/** Updatedat */
			updatedAt: string;
		};
		/** WorkbenchSourceRunPolicyResponse */
		WorkbenchSourceRunPolicyResponse: {
			/** Sessionid */
			sessionId: string;
			/**
			 * Sourcekind
			 * @constant
			 */
			sourceKind: 'liepin';
			/**
			 * Detailopenmode
			 * @enum {string}
			 */
			detailOpenMode: 'human_confirm' | 'bypass_confirm';
			/** Updatedat */
			updatedAt: string;
		};
		/** WorkbenchSourceRunPolicyUpdateRequest */
		WorkbenchSourceRunPolicyUpdateRequest: {
			/**
			 * Detailopenmode
			 * @enum {string}
			 */
			detailOpenMode: 'human_confirm' | 'bypass_confirm';
		};
		/** WorkbenchSourceRunResponse */
		WorkbenchSourceRunResponse: {
			/** Sourcerunid */
			sourceRunId: string;
			/**
			 * Sourcekind
			 * @enum {string}
			 */
			sourceKind: 'cts' | 'liepin';
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'queued' | 'blocked' | 'running' | 'completed' | 'failed';
			/**
			 * Authstate
			 * @enum {string}
			 */
			authState: 'not_required' | 'login_required';
			/** Warningcode */
			warningCode?: string | null;
			/** Warningmessage */
			warningMessage?: string | null;
			/**
			 * Cardsscannedcount
			 * @default 0
			 */
			cardsScannedCount: number;
			/**
			 * Uniquecandidatescount
			 * @default 0
			 */
			uniqueCandidatesCount: number;
			/**
			 * Detailopenusedcount
			 * @default 0
			 */
			detailOpenUsedCount: number;
			/**
			 * Detailopenblockedcount
			 * @default 0
			 */
			detailOpenBlockedCount: number;
		};
		/** WorkbenchSourceRunStartResponse */
		WorkbenchSourceRunStartResponse: {
			/** Sessionid */
			sessionId: string;
			/** Sourcerunid */
			sourceRunId: string;
			/**
			 * Sourcekind
			 * @enum {string}
			 */
			sourceKind: 'cts' | 'liepin';
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'queued' | 'blocked' | 'running' | 'completed' | 'failed';
			job: components['schemas']['WorkbenchSourceRunJobResponse'];
		};
		/** WorkbenchUserResponse */
		WorkbenchUserResponse: {
			/** Userid */
			userId: string;
			/** Email */
			email: string;
			/** Displayname */
			displayName: string;
			/**
			 * Role
			 * @enum {string}
			 */
			role: 'admin' | 'member';
			/** Workspaceid */
			workspaceId: string;
		};
		/** WorkbenchWorkspaceResponse */
		WorkbenchWorkspaceResponse: {
			/** Id */
			id: string;
			/** Name */
			name: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	bootstrap_admin_api_auth_bootstrap_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkbenchBootstrapRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchBootstrapResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	login_api_auth_login_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkbenchLoginRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	logout_api_auth_logout_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path?: never;
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	me_api_auth_me_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchMeResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_sessions_api_workbench_sessions_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSessionListResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_session_api_workbench_sessions_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path?: never;
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkbenchSessionCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSessionResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_session_api_workbench_sessions__session_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSessionResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_candidate_review_items_api_workbench_sessions__session_id__candidates_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchCandidateReviewQueueResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_session_graph_candidates_api_workbench_sessions__session_id__graph_candidates_get: {
		parameters: {
			query: {
				node_id: string;
				limit?: number;
				cursor?: string | null;
			};
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchGraphCandidateListResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_graph_candidate_resume_snapshot_api_workbench_sessions__session_id__graph_candidates__graph_candidate_id__resume_snapshot_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
				graph_candidate_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchGraphCandidateResumeSnapshotResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_source_connections_api_workbench_source_connections_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSourceConnectionListResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_liepin_source_connection_api_workbench_source_connections_liepin_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path?: never;
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSourceConnectionResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_source_connection_api_workbench_source_connections__connection_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				connection_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSourceConnectionResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	start_liepin_connection_login_api_workbench_source_connections__connection_id__login_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				connection_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchLiepinLoginHandoffResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	liepin_connection_login_frame_api_workbench_source_connections__connection_id__login_frame_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				connection_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'text/html': string;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	liepin_connection_login_snapshot_api_workbench_source_connections__connection_id__login_snapshot_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				connection_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						[key: string]: unknown;
					};
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	liepin_connection_login_input_api_workbench_source_connections__connection_id__login_input_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				connection_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkbenchLiepinLoginRelayInputRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						[key: string]: unknown;
					};
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	complete_liepin_connection_login_api_workbench_source_connections__connection_id__login_complete_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				connection_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSourceConnectionResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	update_candidate_review_item_api_workbench_sessions__session_id__candidates__review_item_id__put: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				session_id: string;
				review_item_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkbenchCandidateReviewItemUpdateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchCandidateReviewItemResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	open_candidate_provider_action_api_workbench_sessions__session_id__candidates__review_item_id__provider_actions_open_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				session_id: string;
				review_item_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchProviderActionResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_detail_open_request_api_workbench_sessions__session_id__candidates__review_item_id__detail_open_requests_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				session_id: string;
				review_item_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkbenchDetailOpenRequestCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchDetailOpenRequestResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_detail_open_requests_api_workbench_detail_open_requests_get: {
		parameters: {
			query?: {
				session_id?: string | null;
				status?: ('pending' | 'approved' | 'rejected' | 'bypassed' | 'blocked' | 'expired') | null;
			};
			header?: never;
			path?: never;
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchDetailOpenRequestListResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	approve_detail_open_request_api_workbench_detail_open_requests__request_id__approve_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				request_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchDetailOpenRequestResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	reject_detail_open_request_api_workbench_detail_open_requests__request_id__reject_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				request_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkbenchDetailOpenRejectRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchDetailOpenRequestResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_requirement_triage_api_workbench_sessions__session_id__triage_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchRequirementTriageResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	update_requirement_triage_api_workbench_sessions__session_id__triage_put: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkbenchRequirementTriageUpdateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchRequirementTriageResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	prepare_requirement_triage_api_workbench_sessions__session_id__triage_prepare_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchRequirementTriageResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	approve_requirement_triage_api_workbench_sessions__session_id__triage_approve_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchRequirementTriageResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	start_session_source_runs_api_workbench_sessions__session_id__start_post: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSessionStartResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_liepin_source_run_policy_api_workbench_sessions__session_id__source_runs_liepin_policy_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSourceRunPolicyResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	update_liepin_source_run_policy_api_workbench_sessions__session_id__source_runs_liepin_policy_put: {
		parameters: {
			query?: never;
			header?: {
				'X-CSRF-Token'?: string | null;
			};
			path: {
				session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['WorkbenchSourceRunPolicyUpdateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSourceRunPolicyResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_security_audit_events_api_workbench_security_audit_events_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSecurityAuditEventListResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	settings_api_workbench_settings_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchSettingsResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_events_api_workbench_events_get: {
		parameters: {
			query?: {
				after_seq?: number;
				limit?: number;
			};
			header?: never;
			path?: never;
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchEventListResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_session_events_api_workbench_sessions__session_id__events_get: {
		parameters: {
			query?: {
				after_seq?: number;
				limit?: number;
			};
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['WorkbenchEventListResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	stream_events_api_workbench_events_stream_get: {
		parameters: {
			query?: {
				after_seq?: number;
			};
			header?: {
				'Last-Event-ID'?: string | null;
			};
			path?: never;
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	stream_session_events_api_workbench_sessions__workbench_session_id__events_stream_get: {
		parameters: {
			query?: {
				after_seq?: number;
			};
			header?: {
				'Last-Event-ID'?: string | null;
			};
			path: {
				workbench_session_id: string;
			};
			cookie?: {
				seektalent_workbench_session?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_compliance_gate_api_liepin_compliance_gates_post: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LiepinComplianceGateCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LiepinComplianceGateResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_compliance_gate_api_liepin_compliance_gates__gate_ref__get: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path: {
				gate_ref: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LiepinComplianceGateResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	bind_compliance_gate_account_api_liepin_compliance_gates__gate_ref__bind_account_post: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path: {
				gate_ref: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LiepinComplianceGateConnectionRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LiepinComplianceGateActionResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	verify_compliance_gate_api_liepin_compliance_gates__gate_ref__verify_post: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path: {
				gate_ref: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LiepinComplianceGateConnectionRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LiepinComplianceGateActionResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_connection_api_liepin_connections_post: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['LiepinConnectionCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LiepinConnectionResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_connection_api_liepin_connections__connection_id__get: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path: {
				connection_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LiepinConnectionResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_login_url_api_liepin_connections__connection_id__login_url_post: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path: {
				connection_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LiepinLoginUrlResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_connection_stream_token_api_liepin_connections__connection_id__stream_token_post: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path: {
				connection_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	stream_connection_events_api_liepin_connections__connection_id__events_get: {
		parameters: {
			query?: never;
			header?: {
				'Last-Event-ID'?: string | null;
			};
			path: {
				connection_id: string;
			};
			cookie?: {
				liepin_stream_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_run_api_runs_post: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['RunCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	create_run_stream_token_api_runs__run_id__stream_token_post: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	stream_run_events_api_runs__run_id__events_get: {
		parameters: {
			query?: never;
			header?: {
				'Last-Event-ID'?: string | null;
			};
			path: {
				run_id: string;
			};
			cookie?: {
				liepin_stream_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_run_results_api_runs__run_id__results_get: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LiepinRunResultsResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_candidate_detail_api_runs__run_id__candidates__candidate_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				run_id: string;
				candidate_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['CandidateDetailResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_run_api_runs__run_id__get: {
		parameters: {
			query?: never;
			header?: {
				'X-SeekTalent-API-Key'?: string | null;
				'X-Tenant-ID'?: string | null;
				'X-Workspace-ID'?: string | null;
				'X-Actor-ID'?: string | null;
			};
			path: {
				run_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
